var paycheck = 2000;
document.write(paycheck + "<br/>");
paycheck *= 2;
document.write(paycheck + "<br/>");
paycheck -= 500;
document.write(paycheck + "<br/>");
paycheck -= 3500;
document.write(paycheck + "<br/>");
paycheck += 500;
document.write(paycheck + "<br/>");
paycheck -= 80;
document.write(paycheck + "<br/>");
